# Generated by Django 5.1.1 on 2024-09-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='prtice',
            field=models.IntegerField(),
        ),
    ]
